<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../RhiLinux.Core/RhiLinux.Core.csproj" />
    <ProjectReference Include="../RhiLinux.Steam/RhiLinux.Steam.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="RhiLinux.Tests" />
  </ItemGroup>
</Project>
